### ISSUE TITLE
Suggestions for better english translation of duplicates finder

### ISSUE THREAD

**Issue by GvMariani** [bodun56/duplicatesfinder#1]
Ref. duplicatesfinder 1.6.4 sources.

The Lang_en.ts file as-is is affected by various issues:
1. It says "(Select) path find" (lines 21 and 31 of the .ts file - mainwindow.ui lines 14 and 51), but likely it should say "(Select) **path to search**"  (for duplicates) or "(Select) **path for searching**" (duplicates).
2. It says "Start find" (line 47 of the .ts file - mainwindow.ui line 90), but the correct form is "Start **finding**".
3. It uses "fined" as past participle of "find" (lines 270, 275, 279, 284, 285, 290, 295, 300 and 305 of the .ts file - mainwindow.cpp lines 172, 173, 177, 178, 181, 182, 238 and 239), but the right form is "**found**".
4. At the line 285 of .ts file (mainwindow.cpp line 178) "Duplicates not fined" could be better as: "No duplicates found".
5. It says "Mask files"  (lines 67 and 72 of the .ts file - mainwindow.ui lines 134 and 141), but likely it should say "**File masks**".
6. It says "Start delete checked files" (line 87 of the .ts file - mainwindow.ui line 192), but the correct form is "Start **deleting** checked files".
7. It says "Defaults color" (line 148 of the .ts file - mainwindow.ui line 284), but likely it should say "**Default colors**".

Attached you can find the Lang_en.txt (damn GitHub!) modified according the changes proposed above.

Disclaimer: even if I'm working as volunteer maintainer for russian distribution Rosa Linux, I don't know Russian at all, nor can read Cyrillic; so all the above come from looking at the English translation file in Qt Linguist and from some educated guesses, and - while correct for the English part - could be not the real right translation of the original Russian stuff.
[Lang_en.txt](https://github.com/bodun56/duplicatesfinder/files/9852492/Lang_en.txt)

**Comment by bodun56** [comment]
Thanks for the feedback and comments, it will be released soon with your edits

**Comment by GvMariani** [comment]
> Thanks for the feedback and comments, it will be released soon with your edits
Thank you for your work...
I also have in the back-burner a proposal for an italian translation, but I will submit it after the english changes are merged.

**Comment by bodun56** [comment]
The file for translation has already been added
I would be grateful if you could help with the translation into Italian
You can take the [Lang_it.ts](https://github.com/bodun56/duplicatesfinder/blob/main/Lang_it.ts) file and make changes via Qt Linguist so that I can add changes.
Thank you for suggestions for improvement!

**Comment by GvMariani** [comment]
> The file for translation has already been added I would be grateful if you could help with the translation into Italian
 
Glad to help: attached you will find my stab at italian translation (with the usual rename trick to coerce GitHub in accepting the .ts file)...
I think this issue can be closed now, since you published release 1.6.6.

[Lang_it.txt](https://github.com/bodun56/duplicatesfinder/files/9871182/Lang_it.txt)
